#+TITLE: L99: Ninety-Nine Lisp Problems

* Introduction

  I stumbled across [[http://www.ic.unicamp.br/~meidanis/courses/mc336/2006s2/funcional/L-99_Ninety-Nine_Lisp_Problems.html][L99]], and thought it would be fun to work on
  as a spare-time set of challenges.

* Problems

  1) [X] Find the last box of a list. (2015-08-20)
  2) [ ] Find the last but one box of a list.
  3) [ ] Find the K'th element of a 1-indexed list.
  4) [ ] Find the number of elements of a list.
  5) [ ] Reverse a list.
  6) [ ] Find out whether a list is a palindrome.
  7) [ ] Flatten a nested list structure.
  8) [ ] Eliminate consecutive duplicates of list elements.
  9) [ ] Pack consecutive duplicates of list elements into sublists.
  10) [ ] Run-length encoding of a list.
  11) [ ] Modified RLE.
  12) [ ] Decode a modified RLE list.
  13) [ ] Direct RLE encoding.
  14) [ ] Duplicate the elements of a list.
  15) [ ] Replicate the elements of a list given a number of items.
  16) [ ] Drop every N'th element from a list.
  17) [ ] Split a list into two parts: the length of the first part is given.
  18) [ ] Extract a slice from a list.
  19) [ ] Rotate a list N places to the left.
  20) [ ] Remove the K'th element from a list.

